### Create a feedback
POST http://localhost:3003/api/v1/feedback/672fbde75f8b1b23dc66b7d4
Content-Type: application/json

{
  "feedbackText": "Great work environment!",
  "sentimentScore": 5
}

### Get all feedback for a company
GET http://localhost:3003/api/v1/feedback/672f2804883a8ab2d618adad