### Create a Job Seeker
POST http://localhost:3003/api/v1/jobseekers
Content-Type: application/json

{
  "name": "John Doe 456",
  "email": "johndoe456@example.com",
  "password": "securePassword123",
  "skills": ["JavaScript", "Node.js", "Express"],
  "position": "Backend Developer",
  "experience": 5,
  "wellBeingPreferences": ["Work-life balance", "Remote work"]
}

### Get All Job Seekers
GET http://localhost:3003/api/v1/jobseekers